// <auto-generated>
// ReSharper disable All

using Microsoft.EntityFrameworkCore.Design;

namespace KR.MBE.Data.Models
{
    //public partial class RCMSContextFactory : IDesignTimeDbContextFactory<RCMSContext>
    //{
    //    public RCMSContext CreateDbContext(string[] args)
    //    {
    //        return new RcmsContext();
    //    }
    //}
}
// </auto-generated>
