// <auto-generated>
// ReSharper disable All

using KR.MBE.RCMS.Models;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.ChangeTracking;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.SqlTypes;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;

namespace KR.MBE.Data.Models
{
    // ****************************************************************************************************
    // This is not a commercial licence, therefore only a few tables/views/stored procedures are generated.
    // ****************************************************************************************************

    //public partial class RCMSContext : DbContext, IRCMSContext
    //{
    //    public RCMSContext()
    //    {
    //        InitializePartial();
    //    }

    //    public RCMSContext(DbContextOptions<RCMSContext> options)
    //        : base(options)
    //    {
    //        InitializePartial();
    //    }

    //    public DbSet<TbSystemexception> TbSystemexceptions { get; set; } // TB_SYSTEMEXCEPTION
    //    public DbSet<TbTag> TbTags { get; set; } // TB_TAG
    //    public DbSet<TbTag0614> TbTag0614 { get; set; } // TB_TAG_0614
    //    public DbSet<TbTag0704> TbTag0704 { get; set; } // TB_TAG_0704
    //    public DbSet<TbTier> TbTiers { get; set; } // TB_TIER
    //    public DbSet<TbTierhistory> TbTierhistories { get; set; } // TB_TIERHISTORY
    //    public DbSet<TbUser> TbUsers { get; set; } // TB_USER
    //    public DbSet<TbUserhistory> TbUserhistories { get; set; } // TB_USERHISTORY
    //    public DbSet<TbViewjobparameter> TbViewjobparameters { get; set; } // TB_VIEWJOBPARAMETER
    //    public DbSet<TbViewjobtracking> TbViewjobtrackings { get; set; } // TB_VIEWJOBTRACKING

    //    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
    //    {
    //        if (!optionsBuilder.IsConfigured)
    //        {
    //            optionsBuilder.UseSqlServer(@"Data Source=220.117.185.138,8513;Initial Catalog=RCMS;MultipleActiveResultSets=True;Encrypt=false;TrustServerCertificate=true;User ID=sa;Password=%wave1628");
    //        }
    //    }

    //    public bool IsSqlParameterNull(SqlParameter param)
    //    {
    //        var sqlValue = param.SqlValue;
    //        var nullableValue = sqlValue as INullable;
    //        if (nullableValue != null)
    //            return nullableValue.IsNull;
    //        return (sqlValue == null || sqlValue == DBNull.Value);
    //    }

    //    protected override void OnModelCreating(ModelBuilder modelBuilder)
    //    {
    //        base.OnModelCreating(modelBuilder);

    //        //modelBuilder.ApplyConfiguration(new TbSystemexceptionConfiguration());
    //        //modelBuilder.ApplyConfiguration(new TbTagConfiguration());
    //        //modelBuilder.ApplyConfiguration(new TbTag0614Configuration());
    //        //modelBuilder.ApplyConfiguration(new TbTag0704Configuration());
    //        //modelBuilder.ApplyConfiguration(new TbTierConfiguration());
    //        //modelBuilder.ApplyConfiguration(new TbTierhistoryConfiguration());
    //        //modelBuilder.ApplyConfiguration(new TbUserConfiguration());
    //        //modelBuilder.ApplyConfiguration(new TbUserhistoryConfiguration());
    //        //modelBuilder.ApplyConfiguration(new TbViewjobparameterConfiguration());
    //        //modelBuilder.ApplyConfiguration(new TbViewjobtrackingConfiguration());

    //        OnModelCreatingPartial(modelBuilder);
    //    }


    //    partial void InitializePartial();
    //    partial void DisposePartial(bool disposing);
    //    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    //    static partial void OnCreateModelPartial(ModelBuilder modelBuilder, string schema);
    //}
}
// </auto-generated>
